Web page course
J2ZROMERO/Responsive-webPage pull request #1
Opened 2022-09-23 15:54 UTC by J2ZROMERO

> A quick view through the project.

> [Loom video record](https://www.loom.com/share/227f5c8cebed425d80b16b38e9e0851d)
  ** **
>
- Add  .github/workflows/linters.yml
- Add   to node_modules/  to .gitignore.
- Install Web hint.
- Add .hintrc to the root directory.
- Instal Stylelint.
- Add .stylelintrc.json to the root directory.

** **

- Add index.html
 - Add the bootstrap link.
 - Add font-family link (Cocogoose).
 - Add font-family link (Lato).
 - Add bootstrap breakpoint to make responsive design
 - Add style.css 
 - Add flex-box properties to each box model.

** **

- Add script.js 
 - Add array with path of images.
 - Add object function CSS(element,Object.style) to apply styles and attributes.
 - Use for-loop to go through each character and set the image from the array.
 - Add mouseover and mouse-out event on social media icons, logo, and live button.
 - Create a featured speaker section.
 - Add mouse event on each image (about desktop section)
- Add about.html
 - Add about.css
 - Add background hover to each bigger image
 - Add a link on the bottom about and logo image.
 - Add menu layout.
 - Add hover effect on about images.

** **

- Add style.css
 - Add slide event on some elements (continaer mobile, header).
 - Use a flexbox to place elements on the page.
 - Add a background image to the title on the page (desktop and mobile). 
 - Use cursor pointer on links and logo.

2022-09-23 20:14 UTC, cynthiainga requested changes
Hi @J2ZROMERO, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 
- [ ] Nice design 👍 ✌️ 

## Required Changes ♻️

- [ ]  I enjoyed watching your video but is too long 🙃. So as required in the project you should record a video with a maximum length of 5 minutes containing a clear and objective description of the project, presenting the features of the project, a demo of the project, and showing the pages on different screen sizes, and also a highlight about a piece of the code that you finds interesting or is proud of making 😁 😁
- [ ] Please kindly check the comments under the review 👇 👇

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 20:14 UTC, cynthiainga commented on html/about.html
> +        <li class="navTitle"> <a class="link_page" href="../html/about.html"> <h2>About</h2></a></li>
- [ ] I think it should be better to navigate between the pages in the nav bar, kindly on the about page change the `About` link to `Home` so there's a link from the About page to the Home page so then users can navigate between the two pages easily. I suggest you this change because not everyone will know that the logo directs to the home page, it's better that the nav bar also has a link that can direct you to the home page so that the users will find themselves easily when they navigate on your website 🙃 🙃

2022-09-23 20:14 UTC, cynthiainga commented on js/index.js
> +    <li class="col_user"><button class="colab_button"> <span>More</span> <img class="arrow_bu" src="img/arrow.png" alt=""></button></li>
- [ ] I noticed that you decide to add this button but it not working, as it's an additional requirement if you decide to add this button you should make sure that it works correctly it means that when the user clicks the more button user can see all the lectures and the button change to the `LESS` and if the user clicks to the `LESS` button the user can see only two lectures and the button change to `MORE` again, this is the functionality of this button. Please kindly fix that 🙃 😉

2022-09-23 21:47 UTC, J2ZROMERO commented
> Loom video.

[Capstone project](https://www.loom.com/share/9c95686dfbd24176a3d28547488736f3)

- Change the name of the link on about.html  [about to Home].
- Use the nav tag to grab the links to navigate.
- The function of the button is not a requirement but, I will implement it as soon as possible.

2022-09-23 22:33 UTC, J2ZROMERO commented
> Loom video.

[Capstone project](https://www.loom.com/share/9c95686dfbd24176a3d28547488736f3)

- Change the name of the link on about.html  [about to Home].
- Use the nav tag to grab the links to navigate.
- The function of the button is not a requirement but, of course, I would like to implement it later.

2022-09-23 22:45 UTC, Ismailco requested changes
#### Hi @J2ZROMERO, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-23 22:45 UTC, Ismailco commented on js/index.js
> +    <li class="col_user"><button class="colab_button"> <span>More</span> <img class="arrow_bu" src="img/arrow.png" alt=""></button></li>
- [ ] As the previous reviewer mentioned kindly make sure the More button is working and it's not just a placeholder, so when the user clicks the button all the speakers are displayed and the button disappears or changes to the `Less` button which reduces the number of speakers.

![Screenshot_20220923_233941](https://user-images.githubusercontent.com/25227022/192066119-7a817fe4-1e13-44ea-9f2e-502b06a09baf.png)

2022-09-24 03:50 UTC, J2ZROMERO commented
> Apply to see more event on the button mobile version.

- Before clicking on the button: More

![Before: See more](https://user-images.githubusercontent.com/63516282/192078741-d7c29a41-2c7d-4a3a-a572-8fd5fceaf3b7.png)

- After clicking on the button: More

![2022-09-23_22h45_18](https://user-images.githubusercontent.com/63516282/192078781-6847d1dd-9c3a-4f7f-8539-f729f2e9c7e3.png)

2022-09-24 04:11 UTC, danielufeli approved these changes
Hi @J2ZROMERO ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Design ✔️

## Optional suggestions
- [Optional] Kindly update your ReadMe 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 04:17 UTC, merged